version: '3'

networks:
  backend:
  frontend:

services:
  ### node #########################################
  nextjs-blog:
    container_name: nextjs-blog
    networks:
      - frontend
      - backend
    restart: always
    image: node:18.5.0
    ports:
      - "3000:3000"
    working_dir: '/usr/src/nextjs-blog/'
    command: "npm run dev"
    volumes:
      - ../:/usr/src/nextjs-blog